name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * 1" }]  # 매주 월요일 자동 실행
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: arenran02
          config_timezone: Asia/Seoul
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_followup: yes
          # plugin_achievements: yes
          # plugin_achievements_threshold: C
          # plugin_achievements_display: compact